### ISSUE TITLE
README Pkg.develop fix

### ISSUE THREAD

**Issue by xlxs4** [Datseris/HacktoberfestHowTo#1]
Hi, thanks a lot for this! In the [README](https://github.com/Datseris/HacktoberfestHowTo/blob/main/README.md?plain=1#L49), I think

> If it is not yet registered, you instead develop the GitHub page of the package, such as Pkg.develop("https://github.com/JuliaDynamics/TransitionIdentifiers.jl").

Should be `Pkg.develop(url="https://github.com/JuliaDynamics/TransitionIdentifiers.jl")` instead

**Comment by Datseris** [comment]
Correct, please do a PR
